---
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black-jupyter
        # It is recommended to specify the latest version of Python
        # supported by your project here, or alternatively use
        language_version: python3.10

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.0
    hooks:
    -   id: mypy

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
